# Insert author details
INSERT INTO `tbl_author` (`name`) VALUES ('Khuswant Singh');
INSERT INTO `tbl_author` (`name`) VALUES ('Nirad C Chaudhary');
INSERT INTO `tbl_author` (`name`) VALUES ('Mulk Raj Anand');
INSERT INTO `tbl_author` (`name`) VALUES ('RK Narayan');
INSERT INTO `tbl_author` (`name`) VALUES ('Raja Rao');
INSERT INTO `tbl_author` (`name`) VALUES ('Anita Desai');
INSERT INTO `tbl_author` (`name`) VALUES ('Nayantara Sehgal');
INSERT INTO `tbl_author` (`name`) VALUES ('Nirad C Chaudhari');
INSERT INTO `tbl_author` (`name`) VALUES ('Salman Rushdie');
INSERT INTO `tbl_author` (`name`) VALUES ('Vikram Seth');
INSERT INTO `tbl_author` (`name`) VALUES ('Amitav Ghosh');
INSERT INTO `tbl_author` (`name`) VALUES ('Arundhati Roy');
INSERT INTO `tbl_author` (`name`) VALUES ('Jhumpa Lahiri');
INSERT INTO `tbl_author` (`name`) VALUES ('Kiran Desai');
INSERT INTO `tbl_author` (`name`) VALUES ('Upmanyu Chatterjee');
INSERT INTO `tbl_author` (`name`) VALUES ('Arvind Adiga');
INSERT INTO `tbl_author` (`name`) VALUES ('Kishwar Desai');
INSERT INTO `tbl_author` (`name`) VALUES ('Jeet Thayil');
INSERT INTO `tbl_author` (`name`) VALUES ('Cyrus Mistry');
INSERT INTO `tbl_author` (`name`) VALUES ('Anuradha Roy');
INSERT INTO `tbl_author` (`name`) VALUES ('Neel Mukherjee');
INSERT INTO `tbl_author` (`name`) VALUES ('Mitch Albom');
INSERT INTO `tbl_author` (`name`) VALUES ('Daniel James Brown');
INSERT INTO `tbl_author` (`name`) VALUES ('Audrey Niffenegger');
INSERT INTO `tbl_author` (`name`) VALUES ('Charles Freeman');
INSERT INTO `tbl_author` (`name`) VALUES ('Thomas de Wesselow');
INSERT INTO `tbl_author` (`name`) VALUES ('Arthur Benjamin');
INSERT INTO `tbl_author` (`name`) VALUES ('Michael M. Woolfson');
INSERT INTO `tbl_author` (`name`) VALUES ('Harper Lee');
INSERT INTO `tbl_author` (`name`) VALUES ('Harper Lee');
INSERT INTO `tbl_author` (`name`) VALUES ('William Shakespeare');
INSERT INTO `tbl_author` (`name`) VALUES ('William Golding');
INSERT INTO `tbl_author` (`name`) VALUES ('John Steinbeck');
INSERT INTO `tbl_author` (`name`) VALUES ('Malcolm Gladwell');
INSERT INTO `tbl_author` (`name`) VALUES ('Malcolm Gladwell');
INSERT INTO `tbl_author` (`name`) VALUES ('Malcolm Gladwell');
INSERT INTO `tbl_author` (`name`) VALUES ('Daniel Kahneman');
INSERT INTO `tbl_author` (`name`) VALUES ('Lauren Groff');
INSERT INTO `tbl_author` (`name`) VALUES ('Ta-Nehisi Coates');
INSERT INTO `tbl_author` (`name`) VALUES ('Melissa Guion');
INSERT INTO `tbl_author` (`name`) VALUES ('Benjamin Graham');
INSERT INTO `tbl_author` (`name`) VALUES ('Peter Lynch');
INSERT INTO `tbl_author` (`name`) VALUES ('Stacy Schiff');
INSERT INTO `tbl_author` (`name`) VALUES ('Janet Evanovich');
INSERT INTO `tbl_author` (`name`) VALUES ('Thug Kitchen');
INSERT INTO `tbl_author` (`name`) VALUES ('The RAND Corporation');
INSERT INTO `tbl_author` (`name`) VALUES ('David Dubowski');
INSERT INTO `tbl_author` (`name`) VALUES ('Graham Johnson');
INSERT INTO `tbl_author` (`name`) VALUES ('Meghan Doherty');
INSERT INTO `tbl_author` (`name`) VALUES ('Theo Nicole Lorenz');
